apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: cli
  name: cli
  namespace: fabric
spec:
  replicas: 1
  selector:
    service: cli
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cli
    spec:
      containers:
#      - command: ["/bin/sh", "-c", "sleep 40000"]
      - command: ["/bin/sh", "-c", "/var/hyperledger/Separete_nodes/k8s/byfn/scripts/script.sh mychannel; sleep 400000"]
        env:
        - name: GOPATH
          value: /opt/gopath
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_ADDRESS
          value: peer0-org1-example-com:7051
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /var/hyperledger/Separete_nodes/k8s/crypto-config/peerOrganizations/org1-example-com/peers/peer0.org1-example-com/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /var/hyperledger/Separete_nodes/k8s/crypto-config/peerOrganizations/org1-example-com/peers/peer0.org1-example-com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /var/hyperledger/Separete_nodes/k8s/crypto-config/peerOrganizations/org1-example-com/peers/peer0.org1-example-com/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/Separete_nodes/k8s/crypto-config/peerOrganizations/org1-example-com/users/Admin@org1-example-com/msp
        image: hyperledger/fabric-tools:x86_64-1.0.1
        imagePullPolicy: ""
        name: cli
        volumeMounts:
        - name: git-volume
          mountPath: /var/hyperledger/
        - name: dockersocket
          mountPath: /host/var/run/docker.sock
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://github.com/Oborysenko/Separete_nodes.git"
      - hostPath:
          path: /var/run/docker.sock
        name: dockersocket
status:
  replicas: 0
