apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: orderer-example-com
  namespace: fabric
spec:
  type: NodePort
  ports:
   - name: "7050"
     nodePort: 30001
     port: 7050
     targetPort: 7050
  selector:
    service: orderer-example-com
status:
  loadBalancer: {}
