apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: peer1-org1-example-com
  namespace: fabric
spec:
  type: ClusterIP
  ports:
   - name: "7051"
     port: 7051
     targetPort: 7051
   - name: "7053"
     port: 7053
     targetPort: 7053
  selector:
    service: peer1-org1-example-com
  clusterIP: 10.0.20.211
status:
  loadBalancer: {}
