apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: orderer-example-com
  name: orderer-example-com
  namespace: fabric
spec:
  replicas: 1
  selector:
    service: orderer-example-com
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: orderer-example-com
    spec:
      containers:
      - command: ["/bin/sh", "-c", "orderer"]
        env:
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/k8s_fabric/channel-artifacts/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/k8s_fabric/crypto-config/ordererOrganizations/example-com/orderers/orderer.example-com/msp

        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LOGLEVEL
          value: DEBUG
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"

        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: "/var/hyperledger/k8s_fabric/crypto-config/ordererOrganizations/example-com/orderers/orderer.example-com/tls/server.key"
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: "/var/hyperledger/k8s_fabric/crypto-config/ordererOrganizations/example-com/orderers/orderer.example-com/tls/server.crt"
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: "[/var/hyperledger/k8s_fabric/crypto-config/ordererOrganizations/example-com/orderers/orderer.example-com/tls/ca.crt]"
          
        - name: FABRIC_CFG_PATH
          value: /var/hyperledger/k8s_fabric/crypto-config/ordererOrganizations/example-com/orderers/orderer.example-com          
        image: hyperledger/fabric-orderer:x86_64-1.0.1
        name: orderer-example-com
        volumeMounts:
        - name: git-volume
          mountPath: /var/hyperledger/
        ports:
        - containerPort: 7050
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://github.com/Oborysenko/k8s_fabric.git"
status:
  replicas: 0
