apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cli
  namespace: fabric
spec:
  type: NodePort
  ports:
   - name: "80"
     nodePort: 30080
     port: 30080
     targetPort: 30080
  selector:
    service: cli
status:
  loadBalancer: {}
